// You are given two strings s and t.
//
// String t is generated by random shuffling string s and then add one more letter at a random position.
//
// Return the letter that was added to t.
//
// Example 1:
//
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.
//   Example 2:
//
// Input: s = "", t = "y"
// Output: "y"

function findTheDifference(s: string, t: string): string {
  if (!s.length) return t[0];

  let sLetters: {[key: string]: number} = {};
  let tLetters: {[key: string]: number} = {};

  for (let i=0; i<s.length; i++){
    sLetters[s[i]] = sLetters[s[i]] ? sLetters[s[i]] + 1 : 1;
  }

  for(let i=0; i<t.length; i++) {
    tLetters[t[i]] = tLetters[t[i]] ? tLetters[t[i]] + 1 : 1;
  }

  for (let key in tLetters) {
    if (!sLetters[key]) return key;

    if (sLetters[key] !== tLetters[key]) return key;
  }

  // for (let i=0; i<t.length; i++) {
  //   if(!s.includes(t[i])) return t[i]
  // }
  //
  return t[0]
}

console.log(findTheDifference('abcd', 'abcde'));
